# The Docker image that will be used to build your app
image: alpine:3.17
pages:
  stage: deploy
  script:
  - date
  artifacts:
    paths:
    - public
  only:
  - master

build-linux:
  before_script:
    - apk add make gcc elfutils-dev ccache
  script:
    - make
