# The Docker image that will be used to build your app
image: ubuntu:22.04
pages:
  stage: deploy
  script:
  - date
  artifacts:
    paths:
    - public
  only:
  - master

build-linux:
  before_script:
    - echo deb-src http://archive.ubuntu.com/ubuntu focal main restricted >> /etc/apt/sources.list
    - DEBIAN_FRONTEND=noninteractive apt-get update -y && apk build-dep -y linux-image-5.15.0-60-generic
  script:
    - make -j$(nproc --ignore=1)
  artifacts:
    paths:
      - build/bzImage.x86_64
